[workspace]
resolver = "2"
members = ["api", "core", "infrastructure", "shared"]

[workspace.dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
actix-web-httpauth = "0.8.0"
sqlx = { version = "0.8.2", features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
    "chrono",
    "macros",
] }
tokio = { version = "1.35.0", features = ["full"] }
log = "0.4.20"
config = "0.13.3"
dotenv = "0.15.0"
env_logger = "0.10.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
chrono = { version = "0.4.31", features = ["serde"] }
thiserror = "1.0.50"
anyhow = "1.0.75"
async-trait = "0.1.74"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
